spring:
  datasource:
    username: root
    password: Rakesh@123
    url: jdbc:mysql://localhost:3306/major
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  data:
    rest:
      base-path: /api

  boot:
    admin:
      client:
        url: http://localhost:1111  # Replace with the actual URL of your Spring Boot Admin Server

management:
  endpoints:
    web:
      exposure:
        include: '*'
